FinalCapstone/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using FinalCapstone.Dal;
using FinalCapstone.Dal.IDAL;
using FinalCapstone.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalCapstone.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationDAL _radiusDAL;

        public LocationController(ILocationDAL radiusDAL)
        {
            _radiusDAL = radiusDAL;
        }

        public double GeoLoc { get; private set; }
        public decimal Longitude { get; private set; }
        public decimal Latitude { get; private set; }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Locations(string id)
        {
            string name;
            double latitude;
            double longitude;

            switch (id)
            {
                case "SN":
                    name = "The Short North";
                    latitude = 39.977133;
                    longitude = -83.004007;
                    break;
                case "PN":
                    name = "Polaris Fashion Place";
                    latitude = 40.145375;
                    longitude = -82.981868;
                    break;
                case "EA":
                    name = "Easton";
                    latitude = 40.050879;
                    longitude = -82.914202;
                    break;
                case "OSU":
                    name = "The OSU Stadium";
                    latitude = 40.014191;
                    longitude = -83.030914;
                    break;
                case "OT":
                    name = "The Ohio Theater";
                    latitude = 41.494549;
                    longitude = -81.795395;
                    break;
                case "SH":
                    name = "The Ohio Statehouse";
                    latitude = 39.961347;
                    longitude = -82.998830;
                    break;
                default:
                    name = "Columbus, OH";
                    latitude = 39.961178;
                    longitude = -82.998795;
                    break;
            }
            IList<Location> Locations = _radiusDAL.LocationsInRadius(name, latitude, longitude);

            return View(Locations);
        }
    }
}

FinalCapstone/Controllers/NeighborhoodController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using FinalCapstone.Dal;
using FinalCapstone.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalCapstone.Controllers
{
    public class NeighborhoodController : Controller
    {
        private readonly INeighborhoodDAL _neighborhoodDAL;
        private const string NewReviewResultKey = nameof(NewReviewResultKey);

        public NeighborhoodController(INeighborhoodDAL neighborhoodDAL)
        {
            _neighborhoodDAL = neighborhoodDAL;
        }

        public double GeoLoc { get; private set; }
        public decimal Longitude { get; private set; }
        public decimal Latitude { get; private set; }

        public IActionResult Neighborhoods(NeighborhoodViewModel model)
        {
            if (TempData.ContainsKey(NewReviewResultKey))
            {
                model.NewReviewResult = TempData[NewReviewResultKey] as string;
            }

            IList<Neighborhood> neighborhoods = _neighborhoodDAL.GetNeighborhoodNames();
            model.Neighborhoods = neighborhoods;

            return View(model);
        }

    }
}

FinalCapstone/Controllers/NewLandmarkController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using FinalCapstone.Dal;
using FinalCapstone.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace FinalCapstone.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class NewLandmarkController : Controller
    {
        private readonly ILandmarkDAL _landmarkDAL;

        public NewLandmarkController(ILandmarkDAL landmarkDAL)
        {
            _landmarkDAL = landmarkDAL;
        }
       
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Landmark model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            else
            {
                _landmarkDAL.SaveLandmark(model);

                return RedirectToAction(nameof(SuccessfulAddition));
            }
        }

        public IActionResult SuccessfulAddition()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalCapstone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="https://images.vexels.com/media/users/3/128933/isolated/preview/b54944f7322722034cfda55e601b4f8d-travel-bus-round-icon-by-vexels.png">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - City Tours</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/main.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="light">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">City Tours</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Neighbordhoods<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="Controllers" asp-controller="Neighborhood" asp-action="Neighborhoods">All Neighborhoods</a></li>
                            <li class="divider"></li>
                            <li><a href="/Landmark/Index/CA">Upper Arlington</a></li>
                            <li><a href="/Landmark/Index/DT">Downtown</a></li>
                            <li><a href="/Landmark/Index/EA">Easton</a></li>
                            <li><a href="/Landmark/Index/PN">Polaris</a></li>
                            <li><a href="/Landmark/Index/SN">Short North</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Itinerary" asp-action="ViewItinerary">Itinerary</a></li>
                    <li><a asp-area="" asp-controller="Location" asp-action="Index">Landmarks</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Itinerary" asp-action="SavedItineraries">Saved Itineraries</a></li>
                        @if (User.Identity.Name.Contains("admin"))
                        {
                            <li><a asp-area="" asp-controller="NewLandmark" asp-action="Index">New Landmark</a></li>
                        }
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>